"""Command line interface: ``python -m week04 <command>``.

Protocol Pro, the design:
  check        Run every compatibility rule on the design
  harness      Pin by pin cable list for every link
  params       Write the ArduPilot parameter file and validate it against 4.7.1
  diagram      Draw the wiring diagram as SVG
  performance  Mass, thrust, hover and flight time
  budget       Bandwidth on every MAVLink link, RTK corrections included
  firmware     What would still work on PX4 or Betaflight, feature by feature, with sources

The protocols:
  journey      Follow one second of RTK corrections through five protocols
  frame        Encode one frame of a protocol and print it (mavlink, crsf, sbus, dshot, can)
  decode       Decode a MAVLink capture (.tlog or raw bytes) with this week's parser

Flight control:
  pid          Simulate the pitch loop for a preset or your own gains, or tune it

Real firmware (needs an ArduPilot checkout with SITL built, see week04/sitl.py):
  sitl         Load the parameters, measure the link budget, test signing and fly this airframe

  docs         Regenerate everything in docs/week04
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path


def _design(args):
    from .design import Design

    return Design.load(getattr(args, "design", None))


def cmd_check(args) -> int:
    from .check import check

    report = check(_design(args))
    if args.json:
        Path(args.json).write_text(json.dumps([f.as_dict() for f in report], indent=1))
    for f in report:
        if f.level != "ok" or args.all:
            print(f"{f.level:8} {f.rule:22} {f.where:20} {f.message}")
    print(f"\n{report.count('error')} errors, {report.count('warning')} warnings, {report.count('ok')} checks passed")
    return 1 if report.count("error") else 0


def cmd_harness(args) -> int:
    from .design import harness

    for c in harness(_design(args)):
        print(f"{c.link}: {c.a} ({c.a_connector}) to {c.b} ({c.b_connector or 'vendor cable'})")
        for w in c.wires:
            print(f"   pin {w.a_pin:>2} {w.a_signal:<14} -> pin {w.b_pin:>2} {w.b_signal:<22} {w.note}")
        for n in c.notes + c.missing:
            print(f"   note: {n}")
    return 0


def cmd_params(args) -> int:
    from . import params

    design = _design(args)
    plist = params.generate(design, gains=_tuned_gains(design) if args.tune else None)
    problems = params.validate(plist)
    if args.out:
        params.write(plist, args.out, header=f"Protocol Pro, {design.spec['firmware']}\nGenerated by python -m week04 params")
        print(f"wrote {args.out}")
    else:
        for p in plist:
            print(f"{p.name:<20} {p.value:<10g} {p.why}")
    for pr in problems:
        print(f"PROBLEM {pr.name} = {pr.value}: {pr.message}")
    print(f"{len(plist)} parameters, {len(problems)} problems against ArduCopter 4.7.1 metadata")
    return 1 if problems else 0


def _tuned_gains(design) -> dict:
    """Rate loop gains for pitch and roll from the pitch simulator on this airframe (ArduPilot units)."""
    from . import pid

    plant = plant_for(design)
    g = pid.tune_cascade(plant)
    scale = 1.0 / plant.tau_max  # ArduPilot rate PIDs output a fraction of full differential thrust
    out = {}
    for axis in ("PIT", "RLL"):
        out[f"ATC_ANG_{axis}_P"] = g.angle_p
        out[f"ATC_RAT_{axis}_P"] = g.kp * scale
        out[f"ATC_RAT_{axis}_I"] = g.ki * scale
        out[f"ATC_RAT_{axis}_D"] = g.kd * scale
    return out


def plant_for(design):
    from . import performance, pid

    perf = performance.analyse(design)
    prop, _ = performance.calibrate(design)
    volts = design.parts["battery"].part["specs"]["nominal_v"]
    hover_each = perf.mass_kg * performance.G / 4
    top = prop.at_throttle(1.0, volts)[0]
    arm = design.parts["frame"].part["specs"].get("arm_length_m", 0.25) / math.sqrt(2)
    tau_max = 4 * min(hover_each, top - hover_each) * arm
    return pid.Plant(inertia=perf.inertia[1], tau_max=round(tau_max, 3))


def cmd_diagram(args) -> int:
    from . import diagram

    Path(args.out).write_text(diagram.render(_design(args)))
    print(f"wrote {args.out}")
    return 0


def cmd_performance(args) -> int:
    from . import performance

    design = _design(args)
    perf = performance.analyse(design)
    _, cal = performance.calibrate(design)
    for name, grams, est in perf.mass_items:
        print(f"  {name:<28} {grams:>7.1f} g{'  (estimate)' if est else ''}")
    d = perf.as_dict()
    d.pop("mass_items")
    print(json.dumps({"performance": d, "calibration": cal}, indent=1))
    return 0


def cmd_budget(args) -> int:
    from . import links

    design = _design(args)
    for link in design.links:
        if not link.spec.get("streams") or not link.spec.get("baud"):
            continue
        b = links.design_budget(design, link)
        print(f"{link.id}: {b.bytes_per_second:.0f} B/s of {b.config.bytes_per_second:.0f} ({100 * b.utilisation:.0f} percent)")
        for stream, bps in sorted(b.by_stream().items(), key=lambda kv: -kv[1]):
            print(f"   {stream:<10} {bps:7.0f} B/s")
        for name, bps in b.extra:
            print(f"   {name:<10} {bps:7.0f} B/s")
    return 0


def cmd_journey(args) -> int:
    from . import journey

    r = journey.run()
    for h in r["hops"]:
        print(
            f"{h['name']:<26} {h['protocol']:<32} {h['units']:>3} units {h['wire_bytes']:>5} B  overhead {100 * h['overhead']:5.1f}%  {1000 * h['seconds']:6.1f} ms"
        )
    print(f"delivered intact: {r['delivered_intact']}, base at {r['base_position']}")
    return 0


def cmd_frame(args) -> int:
    from . import can, dshot, mavlink, rc

    if args.protocol == "mavlink":
        d = mavlink.Dialect.default()
        values = json.loads(args.values or "{}")
        frame = mavlink.encode(d[args.message], values, seq=args.seq)
        print(frame.hex(" "))
    elif args.protocol == "crsf":
        channels = [rc.us_to_raw(float(v)) for v in (args.values or ",".join(["1500"] * 16)).split(",")]
        print(rc.crsf_rc(channels).hex(" "))
    elif args.protocol == "sbus":
        channels = [rc.us_to_raw(float(v)) for v in (args.values or ",".join(["1500"] * 16)).split(",")]
        print(rc.SbusFrame(channels).encode().hex(" "))
    elif args.protocol == "dshot":
        value = dshot.throttle_value(float(args.values or 0.5))
        f = dshot.encode(value, telemetry=False)
        print(f"value {value} frame 0x{f:04X} bits {f:016b}")
    elif args.protocol == "can":
        frame = can.CanFrame(int(args.message or "0x123", 0), bytes.fromhex(args.values or "DEADBEEF"), extended=args.extended)
        bits = frame.wire_bits()
        print("".join(map(str, bits)))
        print(f"{len(bits)} bits, {len(frame.stuffed_bits()) - len(frame.header_bits()) - 15} stuff bits, CRC 0x{frame.crc():04X}")
    return 0


def cmd_decode(args) -> int:
    from . import mavlink

    data = Path(args.path).read_bytes()
    if args.path.endswith(".tlog"):
        entries, parser = mavlink.read_tlog(data)
        packets = [p for _, p in entries]
    else:
        parser = mavlink.Parser()
        packets = list(parser.feed(data))
    names = {}
    for p in packets:
        name, _ = parser.decode(p)
        names[name] = names.get(name, 0) + 1
    for name, n in sorted(names.items(), key=lambda kv: -kv[1])[: args.top]:
        print(f"{n:6}  {name}")
    print(f"{len(packets)} packets, {parser.crc_errors} CRC errors, {parser.lost} lost by sequence number")
    return 0


def cmd_pid(args) -> int:
    from . import pid

    design = _design(args)
    plant = plant_for(design) if args.airframe else pid.Plant()
    if args.tune:
        gains = pid.tune(plant)
    elif args.preset:
        gains = pid.PRESETS[args.preset]
    else:
        gains = pid.Gains(args.kp, args.ki, args.kd)
    sc = pid.Scenario()
    m = pid.metrics(pid.simulate(gains, plant, sc), sc)
    print(f"gains kp {gains.kp:.4g} ki {gains.ki:.4g} kd {gains.kd:.4g}, damping ratio {pid.damping_ratio(gains, plant):.2f}")
    for k, v in m.as_dict().items():
        print(f"  {k:<20} {v if v is None else round(v, 4)}")
    return 0


def cmd_sitl(args) -> int:
    from . import sitl

    root = Path(args.ardupilot) if args.ardupilot else sitl.ardupilot_dir()
    if root is None:
        print("no ArduPilot SITL build found: set ARDUPILOT_DIR (see week04/sitl.py)", file=sys.stderr)
        return 2
    result = sitl.experiments(root, _design(args), window=args.window)
    capture = result.pop("_capture")
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=1))
    if args.capture:
        Path(args.capture).write_bytes(capture)
    print(json.dumps({k: v for k, v in result.items() if k in ("params", "signing", "channel_mapping")}, indent=1))
    return 0


def cmd_firmware(args) -> int:
    from . import firmware

    design = _design(args)
    data = firmware.load()
    need = firmware.required_features(design)
    features = {f["id"]: f for f in data["features"]}
    print(f"{'feature':34s}" + "".join(f"{firmware.NAMES[fw]:12s}" for fw in firmware.FIRMWARES))
    for fid in need:
        f = features[fid]
        print(f"{f['feature'][:33]:34s}" + "".join(f"{firmware.SYMBOL[f[fw]['support']]:12s}" for fw in firmware.FIRMWARES))
    for fw, v in firmware.verdicts(design, data).items():
        lost = ", ".join(v.lost) or "nothing"
        print(f"{firmware.NAMES[fw]}: {len(v.supported)} of {len(need)} supported, {len(v.partial)} with changes, lost: {lost}")
    return 0


def cmd_docs(args) -> int:
    from . import docs

    docs.build(Path(args.out), run_sitl=args.sitl)
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="week04", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--design", help="design JSON (default week04/data/design.json)")
    sub = ap.add_subparsers(dest="command", required=True)

    s = sub.add_parser("check")
    s.add_argument("--all", action="store_true", help="also list passed checks")
    s.add_argument("--json")
    s.set_defaults(func=cmd_check)
    sub.add_parser("harness").set_defaults(func=cmd_harness)
    s = sub.add_parser("params")
    s.add_argument("--out")
    s.add_argument("--tune", action="store_true", help="include rate loop gains tuned on this airframe")
    s.set_defaults(func=cmd_params)
    s = sub.add_parser("diagram")
    s.add_argument("--out", default="wiring.svg")
    s.set_defaults(func=cmd_diagram)
    sub.add_parser("performance").set_defaults(func=cmd_performance)
    sub.add_parser("budget").set_defaults(func=cmd_budget)
    sub.add_parser("firmware").set_defaults(func=cmd_firmware)
    sub.add_parser("journey").set_defaults(func=cmd_journey)
    s = sub.add_parser("frame")
    s.add_argument("protocol", choices=["mavlink", "crsf", "sbus", "dshot", "can"])
    s.add_argument("--message", help="MAVLink message name, or CAN identifier")
    s.add_argument("--values", help="MAVLink fields as JSON, channel microseconds, throttle, or CAN data hex")
    s.add_argument("--seq", type=int, default=0)
    s.add_argument("--extended", action="store_true")
    s.set_defaults(func=cmd_frame)
    s = sub.add_parser("decode")
    s.add_argument("path")
    s.add_argument("--top", type=int, default=20)
    s.set_defaults(func=cmd_decode)
    s = sub.add_parser("pid")
    s.add_argument("--preset", choices=["preeti", "preeti_darren", "isabelle_too_much", "all_three"])
    s.add_argument("--kp", type=float, default=1.5)
    s.add_argument("--ki", type=float, default=2.0)
    s.add_argument("--kd", type=float, default=0.274)
    s.add_argument("--tune", action="store_true")
    s.add_argument("--airframe", action="store_true", help="use this design's inertia and torque instead of the default plant")
    s.set_defaults(func=cmd_pid)
    s = sub.add_parser("sitl")
    s.add_argument("--ardupilot")
    s.add_argument("--out", default="docs/week04/sitl.json")
    s.add_argument("--capture", default="docs/week04/sitl_flight.tlog")
    s.add_argument("--window", type=float, default=20.0)
    s.set_defaults(func=cmd_sitl)
    s = sub.add_parser("docs")
    s.add_argument("--out", default="docs/week04")
    s.add_argument("--sitl", action="store_true", help="also rerun the SITL experiments (several minutes)")
    s.set_defaults(func=cmd_docs)
    args = ap.parse_args(argv)
    return args.func(args)
